/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        display: ["var(--font-display)", "system-ui", "sans-serif"],
        body: ["var(--font-body)", "monospace"],
      },
      colors: {
        surface: "var(--surface)",
        "surface-elevated": "var(--surface-elevated)",
        "surface-high": "var(--surface-high)",
        border: "var(--border)",
        "border-heavy": "var(--border-heavy)",
        yellow: "var(--yellow)",
        blue: "var(--blue)",
        "yellow-dim": "var(--yellow-dim)",
        "blue-dim": "var(--blue-dim)",
        accent: "var(--accent)",
        "accent-dim": "var(--accent-dim)",
        // shadcn color tokens mapped to brutalist CSS variables
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover: { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        primary: { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary: { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted: { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        "accent-foreground": "var(--accent-foreground)",
        destructive: { DEFAULT: "var(--destructive)", foreground: "oklch(0.985 0 0)" },
        input: "var(--input)",
        ring: "var(--ring)",
        chart: { 1: "var(--chart-1)", 2: "var(--chart-2)", 3: "var(--chart-3)", 4: "var(--chart-4)", 5: "var(--chart-5)" },
        sidebar: { DEFAULT: "var(--sidebar)", foreground: "var(--sidebar-foreground)", primary: "var(--sidebar-primary)", "primary-foreground": "var(--sidebar-primary-foreground)", accent: "var(--sidebar-accent)", "accent-foreground": "var(--sidebar-accent-foreground)", border: "var(--sidebar-border)", ring: "var(--sidebar-ring)" },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "var(--radius)",
        sm: "var(--radius)",
        xl: "var(--radius)",
        "2xl": "var(--radius)",
        "3xl": "var(--radius)",
        "4xl": "var(--radius)",
        full: "var(--radius)",
      },
      keyframes: {
        scroll: { to: { transform: "translate(calc(-50% - 0.5rem))" } },
        snapIn: { from: { opacity: "0", transform: "translateX(-8px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        thudIn: { from: { opacity: "0", transform: "translateY(8px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        fadeIn: { from: { opacity: "0" }, to: { opacity: "1" } },
      },
      animation: {
        scroll: "scroll var(--animation-duration, 40s) var(--animation-direction, forwards) linear infinite",
        "snap-in": "snapIn 0.2s step-end forwards",
        "thud-in": "thudIn 0.15s step-end forwards",
        "fade-in": "fadeIn 0.2s step-end forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
